### ISSUE TITLE
Shield and Armor Values mixed up

### ISSUE THREAD

**Issue by Meatroach** [steemnova/steemnova#194] opened 2020-01-08 11:29 UTC
I installed SteemNova on my Server and am testing it right now. While testing I encountered a bug in the Battlesystem:

![steemnova_battlereport_bug](https://user-images.githubusercontent.com/39348983/71974379-a7d7ec00-3211-11ea-994d-7cfa625fd6c6.jpg)

As you can see the Values for shields (schilde/schildstärke) and armor (hull/strukturpunkte) are mixed up and the shield-value is also too weak by a faktor of 0.1

**Comment by Meatroach** [comment] 2020-01-08 12:04
As you can see the values are also not adding up correctly and are not calculated against the lost of the ships. If I simulate the battle everything looks fine: the values are correct and added up correctly although there is still a factor of 0.1 between the armor-value of the shipdescription and the battlereport (this might be intentional? 4000 Hullpoints seems a bit much, 400 on the other side seems good)

**Comment by mys** [comment] 2020-01-08 12:11
This is caused by OPBE combat engine. Since https://github.com/steemnova/steemnova/commit/7fcd12f9f7ae11d42e67dc2ab5ef71d0866631bf the values of Armor and Shield are mixed wrongly. My proposal is to go back to previous combat engine.

**Comment by Meatroach** [comment] 2020-01-08 12:16
I saw that too and i though this is a result of the mixed values in the first place

**Comment by IntinteDAO** [comment] 2020-01-08 13:00
There is certainly an error in the generation of reports, which should include the number of vessels in the results.

As for +20%, this is due to having officers / research
You have the Hulle on level 2, which gives you an extra 20%.

However, it is worth looking at the engine anyway.

**Comment by Meatroach** [comment] 2020-01-08 13:30
> 
> 
> This is caused by OPBE combat engine. Since [7fcd12f](https://github.com/steemnova/steemnova/commit/7fcd12f9f7ae11d42e67dc2ab5ef71d0866631bf) the values of Armor and Shield are mixed wrongly. My proposal is to go back to previous combat engine.
> 
> EDIT: Look at technologies that multiplies wrong too. It should be 480 Hullpoints and only 10 Shilde per Light Jager.

In the calculateAttack.php I setup the battleengine to "hybrid":

`0 - Ogame probabilistic battle engine (Fast, stable, but buggy)
1 - SteemNova; Slow, unstable on big battles, required custom PHP Extension)
2 - Hybrid; Below 200000 ships SteemNova, Above OPBE
999 - SteemNova's Battle Engine based on Arrays; Very slow, not recommended
*/

$battle_engine = 2;
`

As the fleet in the example is way below 200.000 ships OPBE was not used if i understand correctly. I  tried both battle engines with the same result (mixed values for shield and armor)

@IntinteDAO I recognized this as well and as i mentioned before the research-bonus is calculated to the right category (shield/armor) but with wrong values in the first place (shield-value for armor and vice versa)

I appreciate your work guys, thank you very much!

**Comment by mys** [comment] 2020-01-08 13:57
https://steemnova1.intinte.org/game.php?page=raport&mode=battlehall&raport=d9d2fa375db1c0d8d31be9ef25182d38
This is example battle from before patch (30. Sep 2019). Values of Shield and Armor + tech% are accurate.

**Comment by IntinteDAO** [comment] 2020-01-08 14:24
@Meatroach 

Yes, although in our instance it's changed. The whole problem with the hybrid system is that we have either a very good but slow engine for small battles, or worse, fast for big ones.

Personally, I would prefer only one to be with the best precision, but optimized. Unfortunately, we don't have one.

In my opinion this is a big problem, which was controversial (having two battle engines). Because you simulate a battle and can give a different result, because the planet you are attacking has built more defense, so another engine has activated, which gave different results than in simulator.

**Comment by Meatroach** [comment] 2020-01-08 14:37
Which system do you use then if I may ask?

**Comment by IntinteDAO** [comment] 2020-01-08 15:20
0 - OPBE only

**Comment by Meatroach** [comment] 2020-01-10 15:35
I switched the getHull() and getShield()-Function in OPBE.php on line 242 with each other and I get the right values in the Battle-Report but still with the wrong tech-multiplier. I do not know if this is a right approach at all...


line 242: `array ('shield' => $shipType->getShield(),'def' => $shipType->getHull),'att' => $shipType->getPower());`

to

line 242: `array ('shield' => $shipType->getHull(),'def' => $shipType->getShield(),'att' => $shipType->getPower());`

**Comment by Qwatayean** [comment] 2020-01-10 15:50
you may get the wrong tech multiplier because they may be swapped just like
ship attributes. Possibly will only require the "dirty job" of swapping
tech id. I'll take a look into this tonight.

Meatroach <notifications@github.com> escreveu no dia sexta, 10/01/2020 à(s)
15:36:

**Comment by Qwatayean** [comment] 2020-01-11 02:39
In addition to what you have said,

on getTechsFromArray from OPBE.php...

the $shieldTech = $player['shield_tech'] and  $defenceTech = $player['defence_tech']
should become $shieldTech = $player['defence_tech'] and  $defenceTech = $player['shield_tech'], 

And you start getting the correct tech bonuses applied to the ship.

This also makes that on GeneralReport.php the disposition of techs in header are wrong...
where 'tech'		=> array($player['techs'][0] * 100, $player['techs'][1] * 100, $player['techs'][2] * 100)
should become 'tech'		=> array($player['techs'][0] * 100, $player['techs'][2] * 100, $player['techs'][1] * 100)
... in both defense and attack.

After doing such changes, that's how a post-report looked like:

![download](https://user-images.githubusercontent.com/36681655/72197647-93ffd600-341b-11ea-9d3f-51d482b9e112.png)

**Comment by IntinteDAO** [comment] 2020-01-16 13:50
I think we should try to rewrite these values. Because then in this mess, the new programmer won't know why it works like this. I don't know if I can do it... but I will try ;)

**Comment by IntinteDAO** [comment] 2020-01-17 14:36
> edit: also, the stats do not add up so there is still the shield-stat for i.e. only one light fighter. This seems to be only visual

Fixed in:
https://github.com/steemnova/steemnova/commit/186d00d6a8d4a236c9eeb21aebb8b93f17cdc6e6

**Comment by IntinteDAO** [comment] 2020-01-20 20:05
After thousands of hours and hundreds of billions spent on the committee, I find that the bug is in code 2moons, which gives the wrong values, and it is best to "fix" them in the OPBE engine (by changing Shield and Armor).

**Comment by IntinteDAO** [comment] 2020-01-22 10:43
Fixed in: https://github.com/steemnova/steemnova/commit/8fbaebca328f05545bb1ec4903b407cdbaffdf0a

**Closed by IntinteDAO** 2020-01-22 10:43 UTC
Labels: bug
